sudo: false

language: erlang

matrix:
  fast_finish: true

  # Jobs that are allowed to fail:
  allow_failures:
    - env: TEST=".travis/travis_has_latest_otp_version"
    - env: TEST="make gradualize"

  include:

  # Check that the latest Erlang version is tested

  # This test will fail with 'X' when a new version is available via kerl.
  # At that point, update THIS test's otp_release to the new one.
  # The test will keep failing with '!', until Travis has the new version.
  # When the test starts failing with 'X' again, Travis has the new version.
  # At that point, update otp_release in the corresponding list below

  - env: TEST=".travis/travis_has_latest_otp_version"
    # Latest minor version of current OTP release
    otp_release: 23.1

  # Run make target specialized for the checks we want to make in Travis for
  # the latest OTP release.
  # Includes coverage report and dialyzer .
  - env: TEST="make travischeck" ENABLE_COVER=true
    # Latest minor version of current OTP release
    otp_release: 23.0

  - env: TEST="make gradualize"
    # Latest minor version of current OTP release
    otp_release: 23.0

# OTP releases that we test in the same way.
# The latest OTP version is special and therefore explicitly
# included above instead.
otp_release:
  # First minor version of current OTP release
  - 23.0
  # Last minor version of older OTP releases
  - 22.2
  - 21.3

env:
  - TEST="make tests"

script:
 - $TEST

after_success:
  - .travis/after_success
