name: Build and test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Erlang ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['25.3', '26.2', '27.2']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: "Build"
        run: "make"
      - name: "Run tests"
        run: "make tests"
