name: Property based tests

on:
  push:
    branches:
      - main
      - master
  pull_request: []

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.3.4.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: "Run property-based tests"
        run: "PROP_NUMTESTS=5000 rebar3 ct --suite test/gradualizer_prop_SUITE.erl"
