on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Publish to Hex.pm
        uses: erlangpack/github-action@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
